# Generated by Django 2.0.1 on 2023-05-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20230513_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
