# Generated by Django 2.2.7 on 2023-05-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_auto_20230513_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenquiz',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='classroom.Team'),
        ),
    ]
