# Generated by Django 2.2.7 on 2023-05-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_quiz_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takenquiz',
            name='team',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='classroom.Team'),
        ),
    ]
